module.exports = {
  MONTHS: [
    "January",
    "February",
    "March",
    "April",
    "May",
    "June",
    "July",
    "August",
    "September",
    "October",
    "November",
    "December",
  ],
  SHORT_MONTHS: [
    "Jan",
    "Feb",
    "Mar",
    "Apr",
    "May",
    "Jun",
    "Jul",
    "Aug",
    "Sep",
    "Oct",
    "Nov",
    "Dec",
  ],
  DAYS: [
    "Sunday",
    "Monday",
    "Tuesday",
    "Wednesday",
    "Thursday",
    "Friday",
    "Saturday",
  ],
  SHORT_DAYS: ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"],
  CHARACTERS: ["Y", "y", "M", "m", "D", "d", "H", "h", "I", "i", "S", "s"],
  TIME_UNITS: [
    { unit: "years", divisor: 31536000000 },
    { unit: "months", divisor: 2592000000 },
    { unit: "weeks", divisor: 604800000 },
    { unit: "days", divisor: 86400000 },
    { unit: "hours", divisor: 3600000 },
    { unit: "minutes", divisor: 60000 },
    { unit: "seconds", divisor: 1000 },
  ],
  FORMAT_MAP: {
    Y: this.year,
    y: this.yr,
    M: this.month,
    m: this.mon,
    W: this.day,
    w: this.dy,
    D: this.date,
    d: this.date.toString().replace(/^0+/, ""),
    H: this.hours,
    h: this.hours % 12,
    I: this.mins < 10 ? `0${this.mins}` : this.mins,
    i: this.mins.toString().replace(/^0+/, ""),
    S: this.secs < 10 ? `0${this.secs}` : this.secs,
    s: this.secs.toString().replace(/^0+/, ""),
    A: this.ampm,
    a: this.ampm.toLowerCase(),
    z: this.suffix,
  },
};
