module.exports = {
  MONTHS: [
    "January",
    "February",
    "March",
    "April",
    "May",
    "June",
    "July",
    "August",
    "September",
    "October",
    "November",
    "December",
  ],
  SHORT_MONTHS: [
    "Jan",
    "Feb",
    "Mar",
    "Apr",
    "May",
    "Jun",
    "Jul",
    "Aug",
    "Sep",
    "Oct",
    "Nov",
    "Dec",
  ],
  DAYS: [
    "Sunday",
    "Monday",
    "Tuesday",
    "Wednesday",
    "Thursday",
    "Friday",
    "Saturday",
  ],
  SHORT_DAYS: ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"],
  TIME_UNITS: [
    { unit: "years", divisor: 31536000000 },
    { unit: "months", divisor: 2592000000 },
    { unit: "weeks", divisor: 604800000 },
    { unit: "days", divisor: 86400000 },
    { unit: "hours", divisor: 3600000 },
    { unit: "minutes", divisor: 60000 },
    { unit: "seconds", divisor: 1000 },
  ],
};
