module.exports = {
  MONTHS: [
    "January",
    "February",
    "March",
    "April",
    "May",
    "June",
    "July",
    "August",
    "September",
    "October",
    "November",
    "December",
  ],
  SHORT_MONTHS: [
    "Jan",
    "Feb",
    "Mar",
    "Apr",
    "May",
    "Jun",
    "Jul",
    "Aug",
    "Sep",
    "Oct",
    "Nov",
    "Dec",
  ],
  DAYS: [
    "Sunday",
    "Monday",
    "Tuesday",
    "Wednesday",
    "Thursday",
    "Friday",
    "Saturday",
  ],
  SHORT_DAYS: ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"],
  CHARACTERS: ["Y", "y", "M", "m", "D", "d", "H", "h", "I", "i", "S", "s"],
};
